---
name: Validate translation files
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Tar-Minyatur/gettext-validation@v1.0
        with:
          folder: Localization/
